export * as Config from "./config"
export * as Diagnostics from "./diagnostics"
export * as ExampleService from "./example-service"
export * as IdGenerator from "./id-generator"
export * as Runtime from "./runtime"
export * as SecretRedactor from "./secret-redactor"
export * as Settings from "./settings"
export * as Telemetry from "./telemetry"
export * as TestHarness from "./test-harness"
export * as Time from "./time"

export const corePackage = "@rika/core"
